import { motion } from 'framer-motion'
import React, { useEffect, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { AppPage, BackButton, BottomSheet, EmptyState, Icon, PrimaryButton, SecondaryButton } from '../components/Ui'
import { wanderCards } from '../data/mockData'
import { authService } from '../services/authService'
import { isPresetProfile } from '../services/profile'
import { useAppActions, useAppState } from '../state/AppContext'

export function WanderPage({ notify, result=false }) {
  const navigate=useNavigate(); const state=useAppState(); const {dispatch}=useAppActions(); const [flipping,setFlipping]=useState(false); const categories=['全部','戶外','美食','拍照','挑戰']
  const draw=(goToResult=false)=>{if(flipping)return;setFlipping(true);const pool=wanderCards.filter(card=>state.random.category==='全部'||card.category===state.random.category);const choices=pool.filter(card=>card.id!==state.random.current?.id);const next=(choices.length?choices:pool)[Math.floor(Math.random()*(choices.length||pool.length))];window.setTimeout(()=>{dispatch({type:'RANDOM_SET',value:{current:next}});setFlipping(false);if(goToResult)navigate('/wander/result')},520)}
  const current=state.random.current||wanderCards[0]
  const categoryMeta={全部:['wander','隨機驚喜'],戶外:['pin','走走看看'],美食:['briefcase','吃點什麼'],拍照:['scan','記錄生活'],挑戰:['star','試試不同']}
  return <AppPage active="wander" nav className={`wander-page ${result?'wander-result-page':''}`}><header className="wander-brand-header">{result?<BackButton fallback="/wander"/>:<span/>}<div><strong>Transit<span>X</span></strong><small>RANDOM / 亂晃</small></div><span className="wander-index">04 / EXPLORE</span></header><section className="wander-heading"><span className="editorial-kicker">NO PLAN, JUST GO</span><h1>亂晃<span>.</span></h1><p>生活不一定要有目的地，<br/>有時候，走著走著就會遇見驚喜。</p></section><div className="wander-categories" role="tablist" aria-label="亂晃分類">{categories.map((category,index)=><button type="button" role="tab" aria-selected={state.random.category===category} className={`tone-${index+1} ${state.random.category===category?'active':''}`} key={category} onClick={()=>dispatch({type:'RANDOM_SET',value:{category}})}><Icon name={categoryMeta[category][0]} size={20}/><strong>{category}</strong><small>{categoryMeta[category][1]}</small></button>)}</div>{result?<><div className="random-deck result-deck"><div/><div/><motion.article className={`random-result-card tone-${current.category}`} animate={{rotateY:flipping?90:0,y:flipping?-8:0,scale:flipping?1.02:1}} transition={{duration:.26}}><span><Icon name={current.category==='美食'?'briefcase':'wander'} size={18}/>{current.category}</span><small>YOUR RANDOM MISSION / 01</small><strong>{current.title}</strong><p>{current.detail}</p><em>GO SOMEWHERE NEW ↗</em></motion.article></div><div className="wander-actions"><SecondaryButton disabled={flipping} onClick={()=>draw(false)}><Icon name="refresh" size={21}/>再抽一次</SecondaryButton><PrimaryButton onClick={()=>{dispatch({type:'RANDOM_SET',value:{active:current}});notify('挑戰已啟用，出發吧！')}}><Icon name="bus" size={20}/>就去吧！</PrimaryButton></div>{state.random.active?.id===current.id&&<motion.div className="active-challenge" initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}}><Icon name="check" size={17}/>今日挑戰進行中</motion.div>}</>:<><article className={`random-deck ${flipping?'drawing':''}`}><div/><div/><motion.div animate={{rotateY:flipping?90:0,y:flipping?-8:0}} transition={{duration:.26}}><span className="editorial-kicker">TODAY'S RANDOM MISSION</span><h2>準備好了嗎？</h2><strong>抽一張卡，<br/><em>讓今天有點<br/>不一樣。</em></strong><p>不用計畫，隨機出發。</p><small>01 / ?</small></motion.div></article><PrimaryButton className="draw-card-button" disabled={flipping} onClick={()=>draw(true)}><Icon name="refresh"/>{flipping?'正在抽一張…':'抽一張卡片'}</PrimaryButton><p className="wander-bottom-note">GOOD DAYS START SOMEWHERE.</p></>}</AppPage>
}

export function ProfilePage() {
  const navigate=useNavigate(); const [searchParams]=useSearchParams(); const state=useAppState(); const {dispatch}=useAppActions(); const [showAllTrips,setShowAllTrips]=useState(false); const favoriteCount=state.favorites.routes.length+state.favorites.stops.length+state.favorites.destinations.length
  const openTrip=(trip)=>navigate(`/trips/${trip.id}`,{state:{returnTo:'/me'}})
  useEffect(()=>{if(searchParams.get('section')==='favorites')window.requestAnimationFrame(()=>document.getElementById('profile-favorites')?.scrollIntoView({behavior:'smooth',block:'start'}))},[searchParams])
  return <AppPage active="profile" nav className="profile-page">
    <header className="profile-top"><div className="brand-mini">Transit<span>X</span><small>公車・讓移動更簡單</small></div><div><button type="button" className="icon-button" aria-label="通知設定" onClick={()=>navigate('/settings')}><Icon name="bell"/></button><button type="button" className="icon-button" aria-label="開啟設定" onClick={()=>navigate('/settings')}><Icon name="settings"/></button></div></header>
    <section className="profile-identity"><div className="profile-avatar-slot" aria-label="使用者名稱縮寫">{(state.auth.user?.name||'訪客旅人').trim().charAt(0).toUpperCase()}</div><div><span className="editorial-kicker">YOUR SPACE / 05</span><h1>嗨，{state.auth.user?.name||'訪客旅人'}！</h1><p>今天也一起去探索吧。</p><button type="button" onClick={()=>navigate('/login')}>{!state.auth.user?'尚未登入':state.auth.user.provider==='guest'?'訪客模式':'本機示範帳號'} <span>›</span></button></div></section>
    <section className="profile-stats" aria-label="個人統計"><span><strong>{state.savedTrips.length}</strong><small>趟旅程</small></span><span><strong>{favoriteCount}</strong><small>個收藏</small></span><span><strong>{state.random.active?1:0}</strong><small>個挑戰</small></span><span><strong>{state.profiles.filter(profile=>!isPresetProfile(profile)).length}</strong><small>個設定</small></span></section>
    <motion.button type="button" className="next-trip-card" onClick={()=>navigate('/ai')} whileTap={{scale:.985}}><span><small>NEXT JOURNEY</small><strong>下一次，出發去看<br/>不一樣的風景吧！</strong></span><i>↗</i></motion.button>
    <section className="profile-section"><div className="profile-section-title"><h2>我的行程</h2>{state.savedTrips.length>3&&<button type="button" onClick={()=>setShowAllTrips(value=>!value)}>{showAllTrips?'收合行程':'全部行程'} <i>›</i></button>}</div>{state.savedTrips.length?<div className="profile-trip-grid">{state.savedTrips.slice(0,showAllTrips?undefined:3).map((trip,index)=><motion.button type="button" className={`mini-trip-card trip-tone-${index%4+1}`} key={trip.id} onClick={()=>openTrip(trip)} whileTap={{scale:.98}}><span className="mini-trip-art"><Icon name="map" size={24}/></span><strong>{trip.title}</strong><small>{trip.startDate||'尚未指定日期'}・{trip.days?.length||state.tripForm.days} 天</small></motion.button>)}<button type="button" className="mini-trip-card add-mini-trip" onClick={()=>navigate('/ai')}><b>＋</b><strong>規劃新旅程</strong><small>和 AI 一起出發</small></button></div>:<div className="profile-empty-row"><EmptyState title="還沒有儲存的行程" detail="完成 AI 規劃後會顯示在這裡。" action="規劃旅程" onAction={()=>navigate('/ai')}/></div>}</section>
    <section id="profile-favorites" className="profile-section"><div className="profile-section-title"><h2>我的收藏</h2><button type="button" onClick={()=>navigate('/traffic/search')}>尋找公車 <i>›</i></button></div><div className="favorite-summary"><span><b>{state.favorites.routes.length}</b> 公車路線</span><span><b>{state.favorites.stops.length}</b> 常用站牌</span><span><b>{state.favorites.destinations.length}</b> 目的地</span></div>{favoriteCount?<div className="profile-favorite-list">{state.favorites.routes.map(id=><button type="button" key={id} onClick={()=>navigate(`/traffic/routes/${id}`)}><span><Icon name="bus"/></span><b>{state.favoriteLabels?.[id]||id}</b><small>已收藏公車路線</small><i>›</i></button>)}{state.favorites.stops.map(id=>{const stop={name:state.favoriteLabels?.[id]||'舊收藏・請重新搜尋'};return <button type="button" key={id} onClick={()=>navigate(`/traffic/stops/${id}`)}><span><Icon name="pin"/></span><b>{stop?.name||id}</b><small>已收藏站牌</small><i>›</i></button>})}{state.favorites.destinations.map(city=><button type="button" key={city} onClick={()=>{dispatch({type:'TRIP_FORM_SET',value:{destination:city}});navigate('/ai/new')}}><span><Icon name="heart"/></span><b>{city}</b><small>已收藏目的地</small><i>›</i></button>)}</div>:<p className="profile-empty-copy">還沒有收藏；在公車、站牌或目的地卡片點愛心即可加入。</p>}</section>
    <section className="profile-section profile-settings-section"><div className="profile-section-title"><h2>其他設定</h2></div><div className="settings-shortcuts"><button type="button" onClick={()=>navigate('/settings')}><span>◔</span><strong>主題模式</strong><small>{state.settings.theme==='dark'?'深色模式':'淺色模式'}</small></button><button type="button" onClick={()=>navigate('/settings')}><span>⌘</span><strong>交通偏好</strong><small>{state.settings.transitPreference}</small></button><button type="button" onClick={()=>navigate('/settings')}><span>ⓘ</span><strong>關於 TransitX</strong><small>版本 2.0</small></button></div></section>
  </AppPage>
}

export function SettingsPage({ notify }) {
  const navigate=useNavigate(); const state=useAppState(); const {dispatch}=useAppActions(); const [info,setInfo]=useState(''); const set=(key,value,message='設定已儲存')=>{dispatch({type:'SETTING_SET',key,value});notify(message)}
  const accountRows=[['mail','電子郵件',state.auth.user?.email||'尚未綁定'],['i','帳號資訊',!state.auth.user?'未登入・本機資料':state.auth.user.provider==='guest'?'訪客・本機資料':'本機示範帳號']]
  const exportData=()=>{
    const snapshot={profiles:state.profiles.filter(profile=>!isPresetProfile(profile)),savedTrips:state.savedTrips,favorites:state.favorites,settings:state.settings}
    const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}))
    const link=document.createElement('a');link.href=url;link.download='transitx-local-data.json';link.click()
    window.setTimeout(()=>URL.revokeObjectURL(url),1000)
    notify('本機資料已匯出')
  }
  return <AppPage active="profile" nav className="settings-page">
    <header className="settings-header"><BackButton fallback="/me"/><div><h1>設定</h1><p>讓 TransitX 更符合你的使用習慣</p></div><span/></header>
    <button type="button" className="settings-account-card" onClick={()=>navigate('/login')}><span className="settings-avatar">{(state.auth.user?.name||'T').trim().charAt(0).toUpperCase()}</span><span><strong>{state.auth.user?.name||'尚未登入'}</strong><small>{state.auth.user?.email||'資料儲存在此裝置'}</small><em>{state.auth.user?.provider==='guest'?'訪客':state.auth.user?'本機示範帳號':'登入／註冊'}</em></span><i>›</i></button>
    <section className="settings-section"><h2>帳號管理</h2><div className="settings-group">{accountRows.map(([icon,title,detail],index)=><button type="button" className="setting-row" key={title} onClick={()=>index===0?navigate('/login'):setInfo('account')}><span className="setting-icon">{icon==='mail'?<Icon name="mail" size={18}/>:icon==='lock'?<Icon name="lock" size={18}/>:icon}</span><span><strong>{title}</strong>{detail&&<small>{detail}</small>}</span><i>›</i></button>)}</div></section>
    <section className="settings-section"><h2>偏好設定</h2><div className="settings-group"><label className="setting-row"><span className="setting-icon">◔</span><span><strong>主題模式</strong><small>{state.settings.theme==='dark'?'深色模式':'淺色模式'}</small></span><input className="setting-toggle" type="checkbox" checked={state.settings.theme==='dark'} onChange={event=>set('theme',event.target.checked?'dark':'light',event.target.checked?'已切換深色模式':'已切換淺色模式')}/></label><label className="setting-row"><span className="setting-icon"><Icon name="bell" size={18}/></span><span><strong>通知設定</strong><small>本機偏好；尚未啟用推播</small></span><input className="setting-toggle" type="checkbox" checked={state.settings.notifications} onChange={event=>set('notifications',event.target.checked)}/></label><label className="setting-row"><span className="setting-icon">⌖</span><span><strong>交通偏好</strong><small>只安排公車移動</small></span><select aria-label="交通偏好" value={state.settings.transitPreference} onChange={event=>set('transitPreference',event.target.value)}><option>最快抵達</option><option>最少步行</option><option>最少轉乘</option></select></label><label className="setting-row"><span className="setting-icon setting-aa">Aa</span><span><strong>字體大小</strong><small>調整介面文字</small></span><select aria-label="字體大小" value={state.settings.fontSize} onChange={event=>set('fontSize',event.target.value)}><option value="small">小</option><option value="medium">標準</option><option value="large">大</option></select></label></div></section>
    <section className="settings-section"><h2>資料與其他</h2><div className="settings-group"><button type="button" className="setting-row" onClick={()=>setInfo('storage')}><span className="setting-icon">☁</span><span><strong>資料保存</strong><small>{state.settings.syncStatus}</small></span><i className="sync-ok">✓</i></button><button type="button" className="setting-row" onClick={exportData}><span className="setting-icon">⇩</span><span><strong>匯出我的資料</strong><small>建立本機資料副本</small></span><i>›</i></button><button type="button" className="setting-row" onClick={()=>setInfo('faq')}><span className="setting-icon">?</span><span><strong>常見問題</strong><small>查看使用說明</small></span><i>›</i></button><button type="button" className="setting-row" onClick={()=>setInfo('about')}><span className="setting-icon">i</span><span><strong>關於 TransitX</strong><small>版本 2.0</small></span><i>›</i></button></div></section>
    <button type="button" className="logout-button" onClick={()=>{if(state.auth.user){dispatch({type:'AUTH_SET',user:null});notify('已登出，資料仍保留在此裝置')}navigate('/login',{replace:true})}}><Icon name="close" size={19}/>{state.auth.user?'登出帳號':'前往登入'}</button>
    <BottomSheet open={Boolean(info)} title={info==='faq'?'常見問題':info==='storage'?'資料保存':info==='account'?'帳號資訊':'關於 TransitX'} onClose={()=>setInfo('')}>
      <div className="settings-info-content">
        {info==='faq'?<><h3>旅行設定一定要填完嗎？</h3><p>前七題用來建立偏好，第八題其他需求可略過。設定保存在此裝置，之後可以編輯。</p><h3>行程與公車時間是真的嗎？</h3><p>支援 WebGPU 的瀏覽器會嘗試用本機 AI 規劃；它可能產生錯誤，行程仍須由你確認。景點只在地點資料來源查核成功後標示已驗證；餐廳、營業時間與交通分鐘不會由 AI 冒充事實。公車到站由交通部 TDX 提供並顯示資料時間；服務失敗時不會用假 ETA 代替。</p><h3>如何找回資料？</h3><p>可在本頁匯出 JSON 備份。清除瀏覽器資料可能會移除本機內容；目前尚無雲端同步。</p></>:info==='storage'?<p>旅行設定、行程、收藏與偏好已儲存在此裝置的瀏覽器。尚未啟用雲端同步；清除網站資料可能會刪除內容。</p>:info==='account'?<p>{state.auth.user?.provider==='guest'?'目前是訪客模式。':state.auth.user?'目前是本機示範登入，未經真實 Email 或 Google 驗證。':'目前尚未登入。'}資料僅儲存在此裝置。</p>:<p>TransitX 2.0 Reviewed 優先使用瀏覽器本機 AI；地點查核使用 OpenStreetMap Nominatim，公車資料來自交通部 TDX。沒有 WebGPU 的裝置可另行設定 Gemini 伺服器備援，目前未自動提供付費 AI。</p>}
      </div>
      <SecondaryButton onClick={()=>setInfo('')}>我知道了</SecondaryButton>
    </BottomSheet>
  </AppPage>
}

export function LoginPage({ notify }) {
  const navigate=useNavigate(); const {dispatch}=useAppActions(); const [mode,setMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [showPassword,setShowPassword]=useState(false)
  const finish=(promise,message)=>{setLoading(true);setError('');promise.then(user=>{dispatch({type:'AUTH_SET',user});notify(message);navigate('/')}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))}
  return <AppPage className="login-page"><header className="login-top"><span className="brand-mini">Transit<span>X</span><small>公車・讓移動更簡單</small></span><button type="button" className="text-button" onClick={()=>navigate('/')}>先逛逛</button></header><section className="login-hero"><span className="editorial-kicker">GO SOMEWHERE NEW / TRANSITX</span><h1>下一站，<br/><em>去看看不一樣的世界。</em></h1><p>訪客也能使用；資料暫時只保存在此裝置。</p></section><section className="login-card"><button type="button" className="google-button" disabled aria-label="Google 驗證尚未連接"><b>G</b>Google 登入・尚未連接</button><div className="login-divider"><span>或使用本機示範 Email</span></div><div className="auth-mode-tabs" role="tablist" aria-label="登入模式"><button type="button" role="tab" aria-selected={mode==='login'} className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>登入</button><button type="button" role="tab" aria-selected={mode==='register'} className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>註冊</button></div><form className="auth-form" onSubmit={event=>{event.preventDefault();finish(authService.loginWithEmail(email,password,mode),'已進入本機示範模式')}}><label><Icon name="mail"/><input aria-label="Email" type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="輸入 Email"/></label><label><Icon name="lock"/><input aria-label="密碼" type={showPassword?'text':'password'} autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={event=>setPassword(event.target.value)} placeholder="輸入密碼（至少 6 字）"/><button type="button" aria-label={showPassword?'隱藏密碼':'顯示密碼'} onClick={()=>setShowPassword(value=>!value)}>{showPassword?'●':'○'}</button></label><button type="button" className="forgot-password" onClick={()=>setError('本機示範模式沒有寄送重設郵件；請改用訪客模式。')}>忘記密碼？</button>{error&&<div className="login-error" role="alert">{error}</div>}<PrimaryButton type="submit" disabled={loading||!email||!password}>{loading?'處理中…':mode==='register'?'建立示範帳號':'示範登入'} <Icon name="arrow"/></PrimaryButton></form><div className="login-divider second"><span>或</span></div><SecondaryButton className="guest-button" disabled={loading} onClick={()=>finish(authService.guest(),'已進入訪客模式')}>以訪客身分繼續</SecondaryButton><p className="login-privacy">本機示範登入不驗證帳號，也不會同步到雲端。</p></section><footer className="login-footer">TRANSITX <span>MOVE YOUR WAY.</span></footer></AppPage>
}
